Rscript balibase.R ../bb_mft_hot/balibase.1_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.1_colors.txt ../bb_mft_hot/balibase.1_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.206_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.206_colors.txt ../bb_mft_hot/balibase.206_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.20_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.20_colors.txt ../bb_mft_hot/balibase.20_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.212_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.212_colors.txt ../bb_mft_hot/balibase.212_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.216_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.216_colors.txt ../bb_mft_hot/balibase.216_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.217_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.217_colors.txt ../bb_mft_hot/balibase.217_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.218_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.218_colors.txt ../bb_mft_hot/balibase.218_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.219_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.219_colors.txt ../bb_mft_hot/balibase.219_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.21_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.21_colors.txt ../bb_mft_hot/balibase.21_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.220_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.220_colors.txt ../bb_mft_hot/balibase.220_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.221_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.221_colors.txt ../bb_mft_hot/balibase.221_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.222_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.222_colors.txt ../bb_mft_hot/balibase.222_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.223_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.223_colors.txt ../bb_mft_hot/balibase.223_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.224_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.224_colors.txt ../bb_mft_hot/balibase.224_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.225_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.225_colors.txt ../bb_mft_hot/balibase.225_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.226_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.226_colors.txt ../bb_mft_hot/balibase.226_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.227_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.227_colors.txt ../bb_mft_hot/balibase.227_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.228_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.228_colors.txt ../bb_mft_hot/balibase.228_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.229_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.229_colors.txt ../bb_mft_hot/balibase.229_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.22_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.22_colors.txt ../bb_mft_hot/balibase.22_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.230_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.230_colors.txt ../bb_mft_hot/balibase.230_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.231_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.231_colors.txt ../bb_mft_hot/balibase.231_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.232_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.232_colors.txt ../bb_mft_hot/balibase.232_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.233_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.233_colors.txt ../bb_mft_hot/balibase.233_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.234_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.234_colors.txt ../bb_mft_hot/balibase.234_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.235_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.235_colors.txt ../bb_mft_hot/balibase.235_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.236_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.236_colors.txt ../bb_mft_hot/balibase.236_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.237_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.237_colors.txt ../bb_mft_hot/balibase.237_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.239_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.239_colors.txt ../bb_mft_hot/balibase.239_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.23_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.23_colors.txt ../bb_mft_hot/balibase.23_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.240_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.240_colors.txt ../bb_mft_hot/balibase.240_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.241_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.241_colors.txt ../bb_mft_hot/balibase.241_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.242_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.242_colors.txt ../bb_mft_hot/balibase.242_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.243_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.243_colors.txt ../bb_mft_hot/balibase.243_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.244_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.244_colors.txt ../bb_mft_hot/balibase.244_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.245_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.245_colors.txt ../bb_mft_hot/balibase.245_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.246_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.246_colors.txt ../bb_mft_hot/balibase.246_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.247_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.247_colors.txt ../bb_mft_hot/balibase.247_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.248_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.248_colors.txt ../bb_mft_hot/balibase.248_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.249_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.249_colors.txt ../bb_mft_hot/balibase.249_seqorder.txt
