Rscript balibase.R ../bb_mft_hot/balibase.348_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.348_colors.txt ../bb_mft_hot/balibase.348_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.352_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.352_colors.txt ../bb_mft_hot/balibase.352_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.353_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.353_colors.txt ../bb_mft_hot/balibase.353_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.35_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.35_colors.txt ../bb_mft_hot/balibase.35_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.360_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.360_colors.txt ../bb_mft_hot/balibase.360_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.362_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.362_colors.txt ../bb_mft_hot/balibase.362_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.363_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.363_colors.txt ../bb_mft_hot/balibase.363_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.366_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.366_colors.txt ../bb_mft_hot/balibase.366_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.371_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.371_colors.txt ../bb_mft_hot/balibase.371_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.374_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.374_colors.txt ../bb_mft_hot/balibase.374_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.376_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.376_colors.txt ../bb_mft_hot/balibase.376_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.37_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.37_colors.txt ../bb_mft_hot/balibase.37_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.38_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.38_colors.txt ../bb_mft_hot/balibase.38_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.395_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.395_colors.txt ../bb_mft_hot/balibase.395_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.396_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.396_colors.txt ../bb_mft_hot/balibase.396_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.397_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.397_colors.txt ../bb_mft_hot/balibase.397_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.398_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.398_colors.txt ../bb_mft_hot/balibase.398_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.399_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.399_colors.txt ../bb_mft_hot/balibase.399_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.3_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.3_colors.txt ../bb_mft_hot/balibase.3_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.400_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.400_colors.txt ../bb_mft_hot/balibase.400_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.401_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.401_colors.txt ../bb_mft_hot/balibase.401_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.402_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.402_colors.txt ../bb_mft_hot/balibase.402_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.403_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.403_colors.txt ../bb_mft_hot/balibase.403_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.404_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.404_colors.txt ../bb_mft_hot/balibase.404_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.405_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.405_colors.txt ../bb_mft_hot/balibase.405_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.406_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.406_colors.txt ../bb_mft_hot/balibase.406_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.407_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.407_colors.txt ../bb_mft_hot/balibase.407_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.408_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.408_colors.txt ../bb_mft_hot/balibase.408_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.409_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.409_colors.txt ../bb_mft_hot/balibase.409_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.40_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.40_colors.txt ../bb_mft_hot/balibase.40_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.410_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.410_colors.txt ../bb_mft_hot/balibase.410_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.411_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.411_colors.txt ../bb_mft_hot/balibase.411_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.412_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.412_colors.txt ../bb_mft_hot/balibase.412_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.413_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.413_colors.txt ../bb_mft_hot/balibase.413_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.414_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.414_colors.txt ../bb_mft_hot/balibase.414_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.415_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.415_colors.txt ../bb_mft_hot/balibase.415_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.416_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.416_colors.txt ../bb_mft_hot/balibase.416_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.417_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.417_colors.txt ../bb_mft_hot/balibase.417_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.418_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.418_colors.txt ../bb_mft_hot/balibase.418_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.419_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.419_colors.txt ../bb_mft_hot/balibase.419_seqorder.txt
