Rscript balibase.R bb_mft_hot/balibase.41_mafft_cos_res_pair.scr bb_mft_hot/balibase.41_colors.txt bb_mft_hot/balibase.41_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.420_mafft_cos_res_pair.scr bb_mft_hot/balibase.420_colors.txt bb_mft_hot/balibase.420_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.421_mafft_cos_res_pair.scr bb_mft_hot/balibase.421_colors.txt bb_mft_hot/balibase.421_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.422_mafft_cos_res_pair.scr bb_mft_hot/balibase.422_colors.txt bb_mft_hot/balibase.422_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.423_mafft_cos_res_pair.scr bb_mft_hot/balibase.423_colors.txt bb_mft_hot/balibase.423_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.424_mafft_cos_res_pair.scr bb_mft_hot/balibase.424_colors.txt bb_mft_hot/balibase.424_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.425_mafft_cos_res_pair.scr bb_mft_hot/balibase.425_colors.txt bb_mft_hot/balibase.425_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.426_mafft_cos_res_pair.scr bb_mft_hot/balibase.426_colors.txt bb_mft_hot/balibase.426_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.427_mafft_cos_res_pair.scr bb_mft_hot/balibase.427_colors.txt bb_mft_hot/balibase.427_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.428_mafft_cos_res_pair.scr bb_mft_hot/balibase.428_colors.txt bb_mft_hot/balibase.428_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.429_mafft_cos_res_pair.scr bb_mft_hot/balibase.429_colors.txt bb_mft_hot/balibase.429_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.42_mafft_cos_res_pair.scr bb_mft_hot/balibase.42_colors.txt bb_mft_hot/balibase.42_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.430_mafft_cos_res_pair.scr bb_mft_hot/balibase.430_colors.txt bb_mft_hot/balibase.430_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.431_mafft_cos_res_pair.scr bb_mft_hot/balibase.431_colors.txt bb_mft_hot/balibase.431_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.432_mafft_cos_res_pair.scr bb_mft_hot/balibase.432_colors.txt bb_mft_hot/balibase.432_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.433_mafft_cos_res_pair.scr bb_mft_hot/balibase.433_colors.txt bb_mft_hot/balibase.433_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.434_mafft_cos_res_pair.scr bb_mft_hot/balibase.434_colors.txt bb_mft_hot/balibase.434_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.435_mafft_cos_res_pair.scr bb_mft_hot/balibase.435_colors.txt bb_mft_hot/balibase.435_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.436_mafft_cos_res_pair.scr bb_mft_hot/balibase.436_colors.txt bb_mft_hot/balibase.436_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.437_mafft_cos_res_pair.scr bb_mft_hot/balibase.437_colors.txt bb_mft_hot/balibase.437_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.438_mafft_cos_res_pair.scr bb_mft_hot/balibase.438_colors.txt bb_mft_hot/balibase.438_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.439_mafft_cos_res_pair.scr bb_mft_hot/balibase.439_colors.txt bb_mft_hot/balibase.439_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.440_mafft_cos_res_pair.scr bb_mft_hot/balibase.440_colors.txt bb_mft_hot/balibase.440_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.441_mafft_cos_res_pair.scr bb_mft_hot/balibase.441_colors.txt bb_mft_hot/balibase.441_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.442_mafft_cos_res_pair.scr bb_mft_hot/balibase.442_colors.txt bb_mft_hot/balibase.442_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.443_mafft_cos_res_pair.scr bb_mft_hot/balibase.443_colors.txt bb_mft_hot/balibase.443_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.444_mafft_cos_res_pair.scr bb_mft_hot/balibase.444_colors.txt bb_mft_hot/balibase.444_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.445_mafft_cos_res_pair.scr bb_mft_hot/balibase.445_colors.txt bb_mft_hot/balibase.445_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.446_mafft_cos_res_pair.scr bb_mft_hot/balibase.446_colors.txt bb_mft_hot/balibase.446_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.447_mafft_cos_res_pair.scr bb_mft_hot/balibase.447_colors.txt bb_mft_hot/balibase.447_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.448_mafft_cos_res_pair.scr bb_mft_hot/balibase.448_colors.txt bb_mft_hot/balibase.448_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.449_mafft_cos_res_pair.scr bb_mft_hot/balibase.449_colors.txt bb_mft_hot/balibase.449_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.44_mafft_cos_res_pair.scr bb_mft_hot/balibase.44_colors.txt bb_mft_hot/balibase.44_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.450_mafft_cos_res_pair.scr bb_mft_hot/balibase.450_colors.txt bb_mft_hot/balibase.450_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.451_mafft_cos_res_pair.scr bb_mft_hot/balibase.451_colors.txt bb_mft_hot/balibase.451_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.452_mafft_cos_res_pair.scr bb_mft_hot/balibase.452_colors.txt bb_mft_hot/balibase.452_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.453_mafft_cos_res_pair.scr bb_mft_hot/balibase.453_colors.txt bb_mft_hot/balibase.453_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.454_mafft_cos_res_pair.scr bb_mft_hot/balibase.454_colors.txt bb_mft_hot/balibase.454_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.455_mafft_cos_res_pair.scr bb_mft_hot/balibase.455_colors.txt bb_mft_hot/balibase.455_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.456_mafft_cos_res_pair.scr bb_mft_hot/balibase.456_colors.txt bb_mft_hot/balibase.456_seqorder.txt
