Rscript balibase.R ../bb_mft_hot/balibase.457_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.457_colors.txt ../bb_mft_hot/balibase.457_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.458_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.458_colors.txt ../bb_mft_hot/balibase.458_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.459_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.459_colors.txt ../bb_mft_hot/balibase.459_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.45_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.45_colors.txt ../bb_mft_hot/balibase.45_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.460_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.460_colors.txt ../bb_mft_hot/balibase.460_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.461_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.461_colors.txt ../bb_mft_hot/balibase.461_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.462_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.462_colors.txt ../bb_mft_hot/balibase.462_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.463_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.463_colors.txt ../bb_mft_hot/balibase.463_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.464_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.464_colors.txt ../bb_mft_hot/balibase.464_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.465_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.465_colors.txt ../bb_mft_hot/balibase.465_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.466_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.466_colors.txt ../bb_mft_hot/balibase.466_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.467_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.467_colors.txt ../bb_mft_hot/balibase.467_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.468_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.468_colors.txt ../bb_mft_hot/balibase.468_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.469_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.469_colors.txt ../bb_mft_hot/balibase.469_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.470_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.470_colors.txt ../bb_mft_hot/balibase.470_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.471_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.471_colors.txt ../bb_mft_hot/balibase.471_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.473_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.473_colors.txt ../bb_mft_hot/balibase.473_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.475_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.475_colors.txt ../bb_mft_hot/balibase.475_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.477_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.477_colors.txt ../bb_mft_hot/balibase.477_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.478_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.478_colors.txt ../bb_mft_hot/balibase.478_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.47_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.47_colors.txt ../bb_mft_hot/balibase.47_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.482_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.482_colors.txt ../bb_mft_hot/balibase.482_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.484_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.484_colors.txt ../bb_mft_hot/balibase.484_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.487_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.487_colors.txt ../bb_mft_hot/balibase.487_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.48_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.48_colors.txt ../bb_mft_hot/balibase.48_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.490_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.490_colors.txt ../bb_mft_hot/balibase.490_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.492_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.492_colors.txt ../bb_mft_hot/balibase.492_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.493_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.493_colors.txt ../bb_mft_hot/balibase.493_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.494_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.494_colors.txt ../bb_mft_hot/balibase.494_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.495_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.495_colors.txt ../bb_mft_hot/balibase.495_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.496_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.496_colors.txt ../bb_mft_hot/balibase.496_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.497_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.497_colors.txt ../bb_mft_hot/balibase.497_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.499_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.499_colors.txt ../bb_mft_hot/balibase.499_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.49_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.49_colors.txt ../bb_mft_hot/balibase.49_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.500_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.500_colors.txt ../bb_mft_hot/balibase.500_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.501_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.501_colors.txt ../bb_mft_hot/balibase.501_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.502_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.502_colors.txt ../bb_mft_hot/balibase.502_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.503_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.503_colors.txt ../bb_mft_hot/balibase.503_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.505_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.505_colors.txt ../bb_mft_hot/balibase.505_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.508_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.508_colors.txt ../bb_mft_hot/balibase.508_seqorder.txt
