Rscript balibase.R bb_mft_hot/balibase.50_mafft_cos_res_pair.scr bb_mft_hot/balibase.50_colors.txt bb_mft_hot/balibase.50_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.515_mafft_cos_res_pair.scr bb_mft_hot/balibase.515_colors.txt bb_mft_hot/balibase.515_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.518_mafft_cos_res_pair.scr bb_mft_hot/balibase.518_colors.txt bb_mft_hot/balibase.518_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.519_mafft_cos_res_pair.scr bb_mft_hot/balibase.519_colors.txt bb_mft_hot/balibase.519_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.53_mafft_cos_res_pair.scr bb_mft_hot/balibase.53_colors.txt bb_mft_hot/balibase.53_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.54_mafft_cos_res_pair.scr bb_mft_hot/balibase.54_colors.txt bb_mft_hot/balibase.54_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.57_mafft_cos_res_pair.scr bb_mft_hot/balibase.57_colors.txt bb_mft_hot/balibase.57_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.58_mafft_cos_res_pair.scr bb_mft_hot/balibase.58_colors.txt bb_mft_hot/balibase.58_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.59_mafft_cos_res_pair.scr bb_mft_hot/balibase.59_colors.txt bb_mft_hot/balibase.59_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.5_mafft_cos_res_pair.scr bb_mft_hot/balibase.5_colors.txt bb_mft_hot/balibase.5_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.60_mafft_cos_res_pair.scr bb_mft_hot/balibase.60_colors.txt bb_mft_hot/balibase.60_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.61_mafft_cos_res_pair.scr bb_mft_hot/balibase.61_colors.txt bb_mft_hot/balibase.61_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.62_mafft_cos_res_pair.scr bb_mft_hot/balibase.62_colors.txt bb_mft_hot/balibase.62_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.63_mafft_cos_res_pair.scr bb_mft_hot/balibase.63_colors.txt bb_mft_hot/balibase.63_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.64_mafft_cos_res_pair.scr bb_mft_hot/balibase.64_colors.txt bb_mft_hot/balibase.64_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.65_mafft_cos_res_pair.scr bb_mft_hot/balibase.65_colors.txt bb_mft_hot/balibase.65_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.66_mafft_cos_res_pair.scr bb_mft_hot/balibase.66_colors.txt bb_mft_hot/balibase.66_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.67_mafft_cos_res_pair.scr bb_mft_hot/balibase.67_colors.txt bb_mft_hot/balibase.67_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.68_mafft_cos_res_pair.scr bb_mft_hot/balibase.68_colors.txt bb_mft_hot/balibase.68_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.69_mafft_cos_res_pair.scr bb_mft_hot/balibase.69_colors.txt bb_mft_hot/balibase.69_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.71_mafft_cos_res_pair.scr bb_mft_hot/balibase.71_colors.txt bb_mft_hot/balibase.71_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.72_mafft_cos_res_pair.scr bb_mft_hot/balibase.72_colors.txt bb_mft_hot/balibase.72_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.74_mafft_cos_res_pair.scr bb_mft_hot/balibase.74_colors.txt bb_mft_hot/balibase.74_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.75_mafft_cos_res_pair.scr bb_mft_hot/balibase.75_colors.txt bb_mft_hot/balibase.75_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.76_mafft_cos_res_pair.scr bb_mft_hot/balibase.76_colors.txt bb_mft_hot/balibase.76_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.77_mafft_cos_res_pair.scr bb_mft_hot/balibase.77_colors.txt bb_mft_hot/balibase.77_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.78_mafft_cos_res_pair.scr bb_mft_hot/balibase.78_colors.txt bb_mft_hot/balibase.78_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.79_mafft_cos_res_pair.scr bb_mft_hot/balibase.79_colors.txt bb_mft_hot/balibase.79_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.7_mafft_cos_res_pair.scr bb_mft_hot/balibase.7_colors.txt bb_mft_hot/balibase.7_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.80_mafft_cos_res_pair.scr bb_mft_hot/balibase.80_colors.txt bb_mft_hot/balibase.80_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.81_mafft_cos_res_pair.scr bb_mft_hot/balibase.81_colors.txt bb_mft_hot/balibase.81_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.82_mafft_cos_res_pair.scr bb_mft_hot/balibase.82_colors.txt bb_mft_hot/balibase.82_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.83_mafft_cos_res_pair.scr bb_mft_hot/balibase.83_colors.txt bb_mft_hot/balibase.83_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.85_mafft_cos_res_pair.scr bb_mft_hot/balibase.85_colors.txt bb_mft_hot/balibase.85_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.86_mafft_cos_res_pair.scr bb_mft_hot/balibase.86_colors.txt bb_mft_hot/balibase.86_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.88_mafft_cos_res_pair.scr bb_mft_hot/balibase.88_colors.txt bb_mft_hot/balibase.88_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.89_mafft_cos_res_pair.scr bb_mft_hot/balibase.89_colors.txt bb_mft_hot/balibase.89_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.8_mafft_cos_res_pair.scr bb_mft_hot/balibase.8_colors.txt bb_mft_hot/balibase.8_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.94_mafft_cos_res_pair.scr bb_mft_hot/balibase.94_colors.txt bb_mft_hot/balibase.94_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.9_mafft_cos_res_pair.scr bb_mft_hot/balibase.9_colors.txt bb_mft_hot/balibase.9_seqorder.txt
