Rscript balibase.R ../bb_mft_hot/balibase.289_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.289_colors.txt ../bb_mft_hot/balibase.289_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.290_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.290_colors.txt ../bb_mft_hot/balibase.290_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.291_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.291_colors.txt ../bb_mft_hot/balibase.291_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.292_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.292_colors.txt ../bb_mft_hot/balibase.292_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.293_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.293_colors.txt ../bb_mft_hot/balibase.293_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.294_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.294_colors.txt ../bb_mft_hot/balibase.294_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.295_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.295_colors.txt ../bb_mft_hot/balibase.295_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.296_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.296_colors.txt ../bb_mft_hot/balibase.296_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.297_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.297_colors.txt ../bb_mft_hot/balibase.297_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.298_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.298_colors.txt ../bb_mft_hot/balibase.298_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.299_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.299_colors.txt ../bb_mft_hot/balibase.299_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.29_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.29_colors.txt ../bb_mft_hot/balibase.29_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.2_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.2_colors.txt ../bb_mft_hot/balibase.2_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.300_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.300_colors.txt ../bb_mft_hot/balibase.300_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.301_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.301_colors.txt ../bb_mft_hot/balibase.301_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.302_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.302_colors.txt ../bb_mft_hot/balibase.302_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.303_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.303_colors.txt ../bb_mft_hot/balibase.303_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.305_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.305_colors.txt ../bb_mft_hot/balibase.305_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.307_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.307_colors.txt ../bb_mft_hot/balibase.307_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.30_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.30_colors.txt ../bb_mft_hot/balibase.30_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.310_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.310_colors.txt ../bb_mft_hot/balibase.310_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.311_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.311_colors.txt ../bb_mft_hot/balibase.311_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.312_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.312_colors.txt ../bb_mft_hot/balibase.312_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.313_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.313_colors.txt ../bb_mft_hot/balibase.313_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.314_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.314_colors.txt ../bb_mft_hot/balibase.314_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.317_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.317_colors.txt ../bb_mft_hot/balibase.317_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.318_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.318_colors.txt ../bb_mft_hot/balibase.318_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.31_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.31_colors.txt ../bb_mft_hot/balibase.31_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.320_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.320_colors.txt ../bb_mft_hot/balibase.320_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.321_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.321_colors.txt ../bb_mft_hot/balibase.321_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.322_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.322_colors.txt ../bb_mft_hot/balibase.322_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.323_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.323_colors.txt ../bb_mft_hot/balibase.323_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.326_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.326_colors.txt ../bb_mft_hot/balibase.326_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.329_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.329_colors.txt ../bb_mft_hot/balibase.329_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.32_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.32_colors.txt ../bb_mft_hot/balibase.32_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.333_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.333_colors.txt ../bb_mft_hot/balibase.333_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.337_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.337_colors.txt ../bb_mft_hot/balibase.337_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.33_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.33_colors.txt ../bb_mft_hot/balibase.33_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.340_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.340_colors.txt ../bb_mft_hot/balibase.340_seqorder.txt
Rscript balibase.R ../bb_mft_hot/balibase.345_mafft_cos_res_pair.scr ../bb_mft_hot/balibase.345_colors.txt ../bb_mft_hot/balibase.345_seqorder.txt
