Rscript balibase.R bb_mft_hot/balibase.250_mafft_cos_res_pair.scr bb_mft_hot/balibase.250_colors.txt bb_mft_hot/balibase.250_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.251_mafft_cos_res_pair.scr bb_mft_hot/balibase.251_colors.txt bb_mft_hot/balibase.251_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.252_mafft_cos_res_pair.scr bb_mft_hot/balibase.252_colors.txt bb_mft_hot/balibase.252_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.253_mafft_cos_res_pair.scr bb_mft_hot/balibase.253_colors.txt bb_mft_hot/balibase.253_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.254_mafft_cos_res_pair.scr bb_mft_hot/balibase.254_colors.txt bb_mft_hot/balibase.254_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.255_mafft_cos_res_pair.scr bb_mft_hot/balibase.255_colors.txt bb_mft_hot/balibase.255_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.256_mafft_cos_res_pair.scr bb_mft_hot/balibase.256_colors.txt bb_mft_hot/balibase.256_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.257_mafft_cos_res_pair.scr bb_mft_hot/balibase.257_colors.txt bb_mft_hot/balibase.257_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.258_mafft_cos_res_pair.scr bb_mft_hot/balibase.258_colors.txt bb_mft_hot/balibase.258_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.259_mafft_cos_res_pair.scr bb_mft_hot/balibase.259_colors.txt bb_mft_hot/balibase.259_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.25_mafft_cos_res_pair.scr bb_mft_hot/balibase.25_colors.txt bb_mft_hot/balibase.25_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.260_mafft_cos_res_pair.scr bb_mft_hot/balibase.260_colors.txt bb_mft_hot/balibase.260_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.262_mafft_cos_res_pair.scr bb_mft_hot/balibase.262_colors.txt bb_mft_hot/balibase.262_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.263_mafft_cos_res_pair.scr bb_mft_hot/balibase.263_colors.txt bb_mft_hot/balibase.263_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.264_mafft_cos_res_pair.scr bb_mft_hot/balibase.264_colors.txt bb_mft_hot/balibase.264_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.265_mafft_cos_res_pair.scr bb_mft_hot/balibase.265_colors.txt bb_mft_hot/balibase.265_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.266_mafft_cos_res_pair.scr bb_mft_hot/balibase.266_colors.txt bb_mft_hot/balibase.266_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.267_mafft_cos_res_pair.scr bb_mft_hot/balibase.267_colors.txt bb_mft_hot/balibase.267_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.268_mafft_cos_res_pair.scr bb_mft_hot/balibase.268_colors.txt bb_mft_hot/balibase.268_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.269_mafft_cos_res_pair.scr bb_mft_hot/balibase.269_colors.txt bb_mft_hot/balibase.269_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.26_mafft_cos_res_pair.scr bb_mft_hot/balibase.26_colors.txt bb_mft_hot/balibase.26_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.270_mafft_cos_res_pair.scr bb_mft_hot/balibase.270_colors.txt bb_mft_hot/balibase.270_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.271_mafft_cos_res_pair.scr bb_mft_hot/balibase.271_colors.txt bb_mft_hot/balibase.271_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.272_mafft_cos_res_pair.scr bb_mft_hot/balibase.272_colors.txt bb_mft_hot/balibase.272_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.273_mafft_cos_res_pair.scr bb_mft_hot/balibase.273_colors.txt bb_mft_hot/balibase.273_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.274_mafft_cos_res_pair.scr bb_mft_hot/balibase.274_colors.txt bb_mft_hot/balibase.274_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.275_mafft_cos_res_pair.scr bb_mft_hot/balibase.275_colors.txt bb_mft_hot/balibase.275_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.276_mafft_cos_res_pair.scr bb_mft_hot/balibase.276_colors.txt bb_mft_hot/balibase.276_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.277_mafft_cos_res_pair.scr bb_mft_hot/balibase.277_colors.txt bb_mft_hot/balibase.277_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.278_mafft_cos_res_pair.scr bb_mft_hot/balibase.278_colors.txt bb_mft_hot/balibase.278_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.279_mafft_cos_res_pair.scr bb_mft_hot/balibase.279_colors.txt bb_mft_hot/balibase.279_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.280_mafft_cos_res_pair.scr bb_mft_hot/balibase.280_colors.txt bb_mft_hot/balibase.280_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.281_mafft_cos_res_pair.scr bb_mft_hot/balibase.281_colors.txt bb_mft_hot/balibase.281_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.282_mafft_cos_res_pair.scr bb_mft_hot/balibase.282_colors.txt bb_mft_hot/balibase.282_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.283_mafft_cos_res_pair.scr bb_mft_hot/balibase.283_colors.txt bb_mft_hot/balibase.283_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.284_mafft_cos_res_pair.scr bb_mft_hot/balibase.284_colors.txt bb_mft_hot/balibase.284_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.285_mafft_cos_res_pair.scr bb_mft_hot/balibase.285_colors.txt bb_mft_hot/balibase.285_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.286_mafft_cos_res_pair.scr bb_mft_hot/balibase.286_colors.txt bb_mft_hot/balibase.286_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.287_mafft_cos_res_pair.scr bb_mft_hot/balibase.287_colors.txt bb_mft_hot/balibase.287_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.288_mafft_cos_res_pair.scr bb_mft_hot/balibase.288_colors.txt bb_mft_hot/balibase.288_seqorder.txt
