Rscript balibase.R bb_mft_hot/balibase.0_mafft_cos_res_pair.scr bb_mft_hot/balibase.0_colors.txt bb_mft_hot/balibase.0_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.10_mafft_cos_res_pair.scr bb_mft_hot/balibase.10_colors.txt bb_mft_hot/balibase.10_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.119_mafft_cos_res_pair.scr bb_mft_hot/balibase.119_colors.txt bb_mft_hot/balibase.119_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.11_mafft_cos_res_pair.scr bb_mft_hot/balibase.11_colors.txt bb_mft_hot/balibase.11_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.126_mafft_cos_res_pair.scr bb_mft_hot/balibase.126_colors.txt bb_mft_hot/balibase.126_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.128_mafft_cos_res_pair.scr bb_mft_hot/balibase.128_colors.txt bb_mft_hot/balibase.128_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.129_mafft_cos_res_pair.scr bb_mft_hot/balibase.129_colors.txt bb_mft_hot/balibase.129_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.12_mafft_cos_res_pair.scr bb_mft_hot/balibase.12_colors.txt bb_mft_hot/balibase.12_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.130_mafft_cos_res_pair.scr bb_mft_hot/balibase.130_colors.txt bb_mft_hot/balibase.130_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.135_mafft_cos_res_pair.scr bb_mft_hot/balibase.135_colors.txt bb_mft_hot/balibase.135_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.137_mafft_cos_res_pair.scr bb_mft_hot/balibase.137_colors.txt bb_mft_hot/balibase.137_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.139_mafft_cos_res_pair.scr bb_mft_hot/balibase.139_colors.txt bb_mft_hot/balibase.139_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.13_mafft_cos_res_pair.scr bb_mft_hot/balibase.13_colors.txt bb_mft_hot/balibase.13_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.147_mafft_cos_res_pair.scr bb_mft_hot/balibase.147_colors.txt bb_mft_hot/balibase.147_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.14_mafft_cos_res_pair.scr bb_mft_hot/balibase.14_colors.txt bb_mft_hot/balibase.14_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.158_mafft_cos_res_pair.scr bb_mft_hot/balibase.158_colors.txt bb_mft_hot/balibase.158_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.15_mafft_cos_res_pair.scr bb_mft_hot/balibase.15_colors.txt bb_mft_hot/balibase.15_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.162_mafft_cos_res_pair.scr bb_mft_hot/balibase.162_colors.txt bb_mft_hot/balibase.162_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.164_mafft_cos_res_pair.scr bb_mft_hot/balibase.164_colors.txt bb_mft_hot/balibase.164_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.167_mafft_cos_res_pair.scr bb_mft_hot/balibase.167_colors.txt bb_mft_hot/balibase.167_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.169_mafft_cos_res_pair.scr bb_mft_hot/balibase.169_colors.txt bb_mft_hot/balibase.169_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.16_mafft_cos_res_pair.scr bb_mft_hot/balibase.16_colors.txt bb_mft_hot/balibase.16_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.170_mafft_cos_res_pair.scr bb_mft_hot/balibase.170_colors.txt bb_mft_hot/balibase.170_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.171_mafft_cos_res_pair.scr bb_mft_hot/balibase.171_colors.txt bb_mft_hot/balibase.171_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.172_mafft_cos_res_pair.scr bb_mft_hot/balibase.172_colors.txt bb_mft_hot/balibase.172_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.174_mafft_cos_res_pair.scr bb_mft_hot/balibase.174_colors.txt bb_mft_hot/balibase.174_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.175_mafft_cos_res_pair.scr bb_mft_hot/balibase.175_colors.txt bb_mft_hot/balibase.175_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.176_mafft_cos_res_pair.scr bb_mft_hot/balibase.176_colors.txt bb_mft_hot/balibase.176_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.178_mafft_cos_res_pair.scr bb_mft_hot/balibase.178_colors.txt bb_mft_hot/balibase.178_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.179_mafft_cos_res_pair.scr bb_mft_hot/balibase.179_colors.txt bb_mft_hot/balibase.179_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.17_mafft_cos_res_pair.scr bb_mft_hot/balibase.17_colors.txt bb_mft_hot/balibase.17_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.180_mafft_cos_res_pair.scr bb_mft_hot/balibase.180_colors.txt bb_mft_hot/balibase.180_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.182_mafft_cos_res_pair.scr bb_mft_hot/balibase.182_colors.txt bb_mft_hot/balibase.182_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.185_mafft_cos_res_pair.scr bb_mft_hot/balibase.185_colors.txt bb_mft_hot/balibase.185_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.187_mafft_cos_res_pair.scr bb_mft_hot/balibase.187_colors.txt bb_mft_hot/balibase.187_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.18_mafft_cos_res_pair.scr bb_mft_hot/balibase.18_colors.txt bb_mft_hot/balibase.18_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.191_mafft_cos_res_pair.scr bb_mft_hot/balibase.191_colors.txt bb_mft_hot/balibase.191_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.193_mafft_cos_res_pair.scr bb_mft_hot/balibase.193_colors.txt bb_mft_hot/balibase.193_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.195_mafft_cos_res_pair.scr bb_mft_hot/balibase.195_colors.txt bb_mft_hot/balibase.195_seqorder.txt
Rscript balibase.R bb_mft_hot/balibase.19_mafft_cos_res_pair.scr bb_mft_hot/balibase.19_colors.txt bb_mft_hot/balibase.19_seqorder.txt
